<div class="admin-page"><div class="admin-page-inner space-y-6">
    @if (session('status')) <x-admin.alert>{{ session('status') }}</x-admin.alert> @endif
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <x-admin.panel><p class="admin-eyebrow">Outstanding to landlords</p><x-admin.kpi-value :value="\App\Support\Currency::formatCompact($summary['outstanding'])" :exact="$this->formatMoney($summary['outstanding'])" /></x-admin.panel>
        <x-admin.panel><p class="admin-eyebrow">Paid to landlords</p><x-admin.kpi-value :value="\App\Support\Currency::formatCompact($summary['paid'])" :exact="$this->formatMoney($summary['paid'])" /></x-admin.panel>
        <x-admin.panel><p class="admin-eyebrow">Platform fee revenue</p><x-admin.kpi-value :value="\App\Support\Currency::formatCompact($summary['platform'])" :exact="$this->formatMoney($summary['platform'])" /></x-admin.panel>
        <x-admin.panel><p class="admin-eyebrow">Awaiting payout</p><x-admin.kpi-value :value="$summary['awaiting']" /></x-admin.panel>
        <x-admin.panel><p class="admin-eyebrow">Overdue payouts</p><x-admin.kpi-value :value="$summary['overdue'] ?? 0" /><p class="text-xs text-slate-500">Oldest: {{ $summary['oldest'] ?? 0 }} days</p></x-admin.panel>
    </div>
    <x-admin.panel><div class="space-y-4">
        <div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p class="admin-eyebrow">Payout ledger</p><h2 class="admin-panel-title">Landlord settlements</h2><p class="admin-panel-copy">Recording a payout does not initiate a bank transfer. Amounts are preserved from the verified payment.</p></div><div><label class="admin-label" for="settlementFilter">Status</label><select id="settlementFilter" wire:model.live="settlementFilter" class="admin-control admin-control-select"><option value="all">All</option><option value="pending">Awaiting payout</option><option value="due_soon">Due soon</option><option value="partially_paid">Partially paid</option><option value="needs_attention">Needs attention</option><option value="overdue">Overdue</option><option value="paid">Fully paid</option></select></div></div>
        <div class="overflow-x-auto"><table class="min-w-full"><thead class="admin-table-head"><tr><th class="admin-table-head-cell">Transaction</th><th class="admin-table-head-cell">Landlord / property</th><th class="admin-table-head-cell">Entitlement</th><th class="admin-table-head-cell">Paid / outstanding</th><th class="admin-table-head-cell">Status</th><th class="admin-table-head-cell">Action</th></tr></thead><tbody class="admin-table-body">@forelse($transactions as $transaction)<tr class="align-top"><td class="px-4 py-4"><p class="font-mono text-xs">{{ $transaction->reference }}</p><p class="mt-1 text-xs text-slate-500">{{ str($transaction->transaction_type)->replace('_', ' ')->headline() }}</p></td><td class="px-4 py-4 text-sm"><p class="font-medium">{{ $transaction->property?->landlord?->name }}</p><p class="text-xs text-slate-500">{{ $transaction->property?->title }}</p></td><td class="px-4 py-4 text-sm">{{ $this->formatMoney($transaction->settlement_entitlement, $transaction->currency) }}</td><td class="px-4 py-4 text-sm">@if($transaction->settlement_state === 'legacy_paid')<p class="text-xs text-slate-500">Historical payout amount unavailable</p>@else<p>{{ $this->formatMoney($transaction->settlement_paid, $transaction->currency) }}</p><p class="text-xs text-slate-500">{{ $this->formatMoney($transaction->settlement_outstanding, $transaction->currency) }} outstanding</p>@endif</td><td class="px-4 py-4"><span class="admin-badge admin-badge-neutral">{{ $transaction->settlement_state === 'legacy_paid' ? 'Legacy payout recorded' : str($transaction->settlement_state)->replace('_', ' ')->headline() }}</span>@if($transaction->settlement_state !== 'legacy_paid' && $transaction->settlement_attention)<p class="mt-2 text-xs font-medium text-slate-700">{{ $transaction->settlement_attention['label'] }} · {{ $transaction->settlement_attention['days'] === 0 ? 'Today' : $transaction->settlement_attention['days'].' days' }}</p>@endif</td><td class="px-4 py-4 text-sm">@if($transaction->settlement_outstanding > 0)<button wire:click="beginPayout({{ $transaction->id }})" type="button" class="admin-inline-link">Record payout</button>@endif @foreach($transaction->landlordSettlements as $settlement)<p class="mt-2"><button wire:click="beginReversal({{ $settlement->id }})" type="button" class="admin-inline-link text-xs">Reverse {{ $this->formatMoney($settlement->payout_amount, $settlement->currency) }}</button></p>@endforeach</td></tr>@empty<tr><td colspan="6" class="px-4 py-8"><x-admin.empty-state title="No eligible paid property transactions." copy="Inspection booking fees never create landlord payouts." /></td></tr>@endforelse</tbody></table></div>{{ $transactions->links() }}
    </div></x-admin.panel>
    @if($recordingTransactionId)<x-admin.panel><form wire:submit="recordPayout" class="space-y-4"><h2 class="admin-panel-title">Record landlord payout</h2><p class="admin-panel-copy">This records an internal payout entry only. It does not transfer money.</p><div class="grid gap-4 md:grid-cols-2"><div><label class="admin-label">Amount</label><input wire:model="payoutAmount" class="admin-control" inputmode="decimal"><x-input-error :messages="$errors->get('payoutAmount')" /></div><div><label class="admin-label">Reference</label><input wire:model="payoutReference" class="admin-control"></div><div><label class="admin-label">Method</label><input wire:model="payoutMethod" class="admin-control"></div><div><label class="admin-label">Note (internal)</label><input wire:model="payoutNote" class="admin-control"></div></div><button wire:loading.attr="disabled" wire:target="recordPayout" class="admin-button" type="submit"><span wire:loading.remove wire:target="recordPayout">Record payout</span><span wire:loading wire:target="recordPayout">Recording...</span></button></form></x-admin.panel>@endif
    @if($reversingSettlementId)<x-admin.panel><form wire:submit="reversePayout" class="space-y-4"><h2 class="admin-panel-title">Reverse recorded payout</h2><div><label class="admin-label">Reason</label><textarea wire:model="reversalReason" class="admin-control"></textarea><x-input-error :messages="$errors->get('reversalReason')" /></div><button wire:loading.attr="disabled" wire:target="reversePayout" class="admin-button" type="submit">Reverse payout</button></form></x-admin.panel>@endif
</div></div>
