<div class="admin-page"><div class="admin-page-inner space-y-6">
@if(session('status'))<x-admin.alert>{{ session('status') }}</x-admin.alert>@endif
<x-admin.panel><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="admin-eyebrow">Move-in condition</p><h2 class="admin-panel-title">{{ $report->property?->title }}</h2><p class="admin-panel-copy">Record existing condition before the tenant takes possession. Mark irrelevant items not applicable.</p></div><button type="button" onclick="window.print()" class="admin-button admin-button-secondary print:hidden">Print report</button></div></x-admin.panel>
@if(! $report->canBeEditedByLandlord())<x-admin.panel><div class="admin-alert admin-alert-info">This report is {{ str($report->status)->headline() }} and evidence can no longer be changed.</div></x-admin.panel>@else
<x-admin.panel><div class="space-y-4"><div><h3 class="text-lg font-semibold text-slate-950">Add condition photo</h3><p class="admin-panel-copy">Photos are private to the landlord, tenant, and VerifyHomes team.</p></div><div class="grid gap-3 sm:grid-cols-[1fr_auto_auto]"><select wire:model="photoItemId" class="admin-control"><option value="">Overall property</option>@foreach($report->items as $item)<option value="{{ $item->id }}">{{ $item->category }}: {{ $item->label }}</option>@endforeach</select><input id="conditionPhoto" wire:model="photo" type="file" accept="image/jpeg,image/png,image/webp" class="admin-control"><x-camera-capture input-id="conditionPhoto" label="Take photo" kind="condition" facing-mode="environment" /></div>@error('photo')<p class="admin-error">{{ $message }}</p>@enderror<button wire:click="addPhoto" type="button" class="admin-button admin-button-secondary" wire:loading.attr="disabled" wire:target="addPhoto,photo">Add photo</button></div></x-admin.panel>
<div class="space-y-6">@foreach($report->items->groupBy('category') as $category => $group)<x-admin.panel><h3 class="text-lg font-semibold text-slate-950">{{ $category }}</h3><div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($group as $item)<div class="admin-subsurface p-4"><label for="rating-{{ $item->id }}" class="admin-label">{{ $item->label }}</label><select id="rating-{{ $item->id }}" wire:model="items.{{ $item->id }}.rating" class="admin-control"><option value="">Select condition</option>@foreach($ratings as $rating)<option value="{{ $rating }}">{{ str($rating)->replace('_', ' ')->headline() }}</option>@endforeach</select>@error("items.{$item->id}.rating")<p class="admin-error">{{ $message }}</p>@enderror<label class="admin-label mt-3" for="notes-{{ $item->id }}">Note</label><textarea id="notes-{{ $item->id }}" wire:model="items.{{ $item->id }}.notes" rows="3" class="admin-control admin-control-textarea" placeholder="Optional, required when damaged"></textarea>@error("items.{$item->id}.notes")<p class="admin-error">{{ $message }}</p>@enderror</div>@endforeach</div></x-admin.panel>@endforeach</div>
<div class="flex flex-col gap-3 sm:flex-row"><button wire:click="saveDraft" type="button" class="admin-button admin-button-secondary" wire:loading.attr="disabled">Save draft</button><button wire:click="submitToTenant" type="button" class="admin-button admin-button-primary" wire:loading.attr="disabled">Submit to tenant</button></div>@endif
@if($report->photos->isNotEmpty())<x-admin.panel><h3 class="text-lg font-semibold text-slate-950">Landlord evidence</h3><div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach($report->photos->where('source','landlord') as $photo)<a href="{{ route('landlord.move-in-condition-photos.show',$photo) }}" target="_blank"><img src="{{ route('landlord.move-in-condition-photos.show',$photo) }}" alt="Landlord condition evidence" class="aspect-square w-full rounded-xl object-cover"></a>@endforeach</div></x-admin.panel>@endif
</div></div>
