<x-admin-layout page-heading="Staff" :navigation="[]">
    <div class="admin-page"><div class="admin-page-inner space-y-6">
        @if (session('status')) <x-admin.alert>{{ session('status') }}</x-admin.alert> @endif
        @if ($credentials)
            <x-admin.panel><p class="admin-eyebrow">Staff credentials</p><p class="admin-panel-copy">Temporary passwords are shown once. Share them only through a secure channel.</p><dl class="mt-4 space-y-2 text-sm"><div><dt class="font-semibold">Email</dt><dd>{{ $credentials['email'] }}</dd></div><div><dt class="font-semibold">Temporary password</dt><dd class="font-mono">{{ $credentials['password'] }}</dd></div></dl></x-admin.panel>
        @endif
        <x-admin.panel><form method="POST" action="{{ route('admin.staff.store') }}" class="grid gap-4 md:grid-cols-3">@csrf<div><label class="admin-label" for="staff-name">Name</label><input id="staff-name" name="name" class="admin-control" required></div><div><label class="admin-label" for="staff-email">Email</label><input id="staff-email" name="email" type="email" class="admin-control" required></div><div><label class="admin-label" for="staff-phone">Phone</label><input id="staff-phone" name="phone" class="admin-control"></div><div class="md:col-span-3"><button class="admin-button">Create staff account</button></div></form></x-admin.panel>
        <x-admin.panel><div class="overflow-x-auto"><table class="min-w-full"><thead class="admin-table-head"><tr><th class="admin-table-head-cell">Name</th><th class="admin-table-head-cell">Status</th><th class="admin-table-head-cell">Last login</th><th class="admin-table-head-cell">Actions</th></tr></thead><tbody class="admin-table-body">@forelse ($members as $member)<tr><td class="px-4 py-4"><p class="font-medium">{{ $member->name }}</p><p class="text-xs text-slate-500">{{ $member->email }}</p></td><td class="px-4 py-4">{{ $member->suspended_at ? 'Inactive' : 'Active' }}</td><td class="px-4 py-4">{{ $member->last_login_at?->diffForHumans() ?? 'Never' }}</td><td class="px-4 py-4"><div class="flex flex-wrap gap-3">@if ($member->suspended_at)<form method="POST" action="{{ route('admin.staff.reactivate', $member) }}">@csrf<button class="admin-inline-link">Activate</button></form>@else<form method="POST" action="{{ route('admin.staff.suspend', $member) }}">@csrf<button class="admin-inline-link">Deactivate</button></form>@endif<form method="POST" action="{{ route('admin.staff.reset-access', $member) }}">@csrf<button class="admin-inline-link">Reset access</button></form></div></td></tr>@empty<tr><td colspan="4" class="px-4 py-8">No staff accounts yet.</td></tr>@endforelse</tbody></table></div></x-admin.panel>
    </div></div>
</x-admin-layout>
