<x-support-team-layout heading="Dashboard">
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <div class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Open requests</p><p class="mt-2 text-3xl font-semibold">{{ $summary['open'] }}</p></div>
        <div class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Waiting for user</p><p class="mt-2 text-3xl font-semibold">{{ $summary['waiting'] }}</p></div>
        <div class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Resolved today</p><p class="mt-2 text-3xl font-semibold">{{ $summary['resolvedToday'] }}</p></div>
        <a href="{{ route('support-team.requests.index', ['assignment' => 'mine']) }}" class="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-teal-300"><p class="text-sm text-slate-500">Assigned to me</p><p class="mt-2 text-3xl font-semibold">{{ $summary['assignedToMe'] }}</p></a>
        <a href="{{ route('support-team.requests.index', ['assignment' => 'unassigned']) }}" class="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-teal-300"><p class="text-sm text-slate-500">Unassigned</p><p class="mt-2 text-3xl font-semibold">{{ $summary['unassigned'] }}</p></a>
        <a href="{{ route('support-team.requests.index') }}" class="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-teal-300"><p class="text-sm text-slate-500">High / urgent</p><p class="mt-2 text-3xl font-semibold">{{ $summary['highUrgent'] }}</p></a>
    </div>
    <div class="mt-6 rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-200 px-5 py-4"><h2 class="font-semibold">Recent support requests</h2></div><div class="divide-y divide-slate-100">@forelse($recentRequests as $request)<a href="{{ route('support-team.requests.show', $request) }}" class="block px-5 py-4 hover:bg-slate-50"><p class="text-sm font-medium">{{ $request->reference }} · {{ $request->subject }}</p><p class="mt-1 text-xs text-slate-500">{{ $request->user?->name }} · {{ str($request->priority)->headline() }} · {{ str($request->status)->replace('_', ' ')->headline() }} · {{ $request->updated_at->diffForHumans() }}</p></a>@empty<p class="px-5 py-8 text-sm text-slate-500">No support requests yet.</p>@endforelse</div></div>
</x-support-team-layout>
